import streamlit as st
from datetime import datetime
import time
from io import BytesIO

# ----------------------------
# PAGE CONFIG
# ----------------------------
st.set_page_config(
    page_title="ScamShield AI",
    page_icon="🛡️",
    layout="wide"
)

# ----------------------------
# CLEAN DARK GRAY CYBER UI
# ----------------------------
st.markdown("""
<style>

/* Background (dark grey cyber look) */
.stApp {
    background: linear-gradient(135deg, #1c1f26, #0f1117);
    color: white;
}

/* Title glow */
h1 {
    text-shadow: 0 0 10px #00f0ff, 0 0 20px #00f0ff;
}

/* Button */
.stButton > button {
    background: linear-gradient(90deg, #00f0ff, #0066ff);
    color: white;
    border-radius: 10px;
    font-weight: bold;
    border: none;
    box-shadow: 0 0 10px #00f0ff;
}

.stButton > button:hover {
    transform: scale(1.03);
    box-shadow: 0 0 20px #00f0ff;
}

/* Glass card */
.glass {
    background: rgba(255,255,255,0.06);
    padding: 18px;
    border-radius: 15px;
    border: 1px solid rgba(0,240,255,0.25);
    backdrop-filter: blur(10px);
}

/* Risk colors */
.high {color:#ff4d4d; text-shadow:0 0 8px #ff4d4d;}
.medium {color:#ffa500; text-shadow:0 0 8px #ffa500;}
.low {color:#00ff88; text-shadow:0 0 8px #00ff88;}

</style>
""", unsafe_allow_html=True)

# ----------------------------
# SESSION STATE
# ----------------------------
if "history" not in st.session_state:
    st.session_state.history = []

if "last_report" not in st.session_state:
    st.session_state.last_report = ""

# ----------------------------
# HEADER
# ----------------------------
st.markdown("""
    <div style="text-align:center;">
        <h1>🛡️ ScamShield AI</h1>
        <p style="color:#aaa;">Real-time Scam Detection & Cyber Protection System</p>
    </div>
""", unsafe_allow_html=True)

st.divider()

# ----------------------------
# INPUT SECTION
# ----------------------------
col1, col2 = st.columns([2,1])

with col1:
    message = st.text_area("🔍 Enter Message", height=120)

with col2:
    st.markdown("### ⚡ Status")
    st.success("AI Engine Active")
    analyze = st.button("🚀 Analyze")

# ----------------------------
# DETECTION LOGIC
# ----------------------------
def analyze_message(msg):
    msg = msg.lower()

    keywords = ["otp", "login", "verify", "bank", "password", "urgent", "account", "click"]
    found = [k for k in keywords if k in msg]

    score = min(95, len(found) * 20)

    if score >= 70:
        return "HIGH", score, found
    elif score >= 30:
        return "MEDIUM", score, found
    else:
        return "LOW", score, found

# ----------------------------
# PDF GENERATOR (FIX FOR YOUR ISSUE)
# ----------------------------
def create_report(level, score, found, message):
    report = f"""
SCAMSHIELD AI REPORT
-------------------------

Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Message:
{message}

Result:
Risk Level: {level}
Scam Probability: {score}%

Detected Keywords:
{', '.join(found) if found else 'None'}

AI Verdict:
{'High risk phishing attempt detected.' if level=='HIGH' else 'Suspicious patterns found.' if level=='MEDIUM' else 'Message appears safe.'}

-------------------------
Generated by ScamShield AI
"""
    return report

# ----------------------------
# RESULT SECTION
# ----------------------------
if analyze and message.strip():

    level, score, found = analyze_message(message)

    with st.spinner("🧠 AI analyzing message..."):
        time.sleep(1)

    color = "high" if level=="HIGH" else "medium" if level=="MEDIUM" else "low"

    report_text = create_report(level, score, found, message)
    st.session_state.last_report = report_text

    st.markdown(f"""
        <div class="glass">
            <h2 class="{color}">⚠️ {level} RISK DETECTED</h2>
            <h3>📊 Scam Probability: {score}%</h3>
        </div>
    """, unsafe_allow_html=True)

    st.progress(score)

    st.markdown("### 🧠 Analysis")
    if found:
        st.error("Suspicious keywords: " + ", ".join(found))
    else:
        st.success("No strong scam patterns detected")

    # SAVE HISTORY
    st.session_state.history.append({
        "time": datetime.now().strftime("%H:%M:%S"),
        "level": level,
        "score": score,
        "text": message[:60]
    })

    # ----------------------------
    # PDF DOWNLOAD BUTTON (FIXED)
    # ----------------------------
    st.download_button(
        label="📄 Download Report (PDF Text)",
        data=report_text,
        file_name="scam_report.txt",
        mime="text/plain"
    )

# ----------------------------
# HISTORY
# ----------------------------
st.divider()
st.markdown("## 📊 Scan History")

for item in reversed(st.session_state.history[-5:]):
    cls = "high" if item["level"]=="HIGH" else "medium" if item["level"]=="MEDIUM" else "low"

    st.markdown(f"""
    <div class="glass">
        🕒 {item['time']}  
        <b class="{cls}">{item['level']} RISK</b> | {item['score']}%  
        <br>
        💬 {item['text']}...
    </div>
    """, unsafe_allow_html=True)

# ----------------------------
# CLEAN FOOTER (REMOVED HACKATHON TEXT)
# ----------------------------
st.markdown("""
    <hr style="opacity:0.2;">
    <p style="text-align:center; color:#888;">
        ScamShield AI • Cybersecurity Detection System
    </p>
""", unsafe_allow_html=True)